- name: "Delete RDS Instance"
  rds:
     command: delete
     instance_name: "{{ RDS.NODE_NAME }}"
     region: "{{ REGION }}"
  register: result

- debug: var=result.stdout_lines
  when: result | success
  tags:
    - always
