- name: "Create Development RDS Instance"
  cloudformation:
     stack_name: "{{ RDS.STACK_NAME.DEVELOPMENT }}"
     template: "{{ ansible_env.PWD }}/files/cloudformation-rds-withroute53.yaml"
     disable_rollback: true
     template_parameters:
        MasterUsername: "{{ SECRET.AWS.RDS_MYSQL_USER }}"
        MasterUserPassword: "{{ SECRET.AWS.RDS_MYSQL_PASSWORD}}"
        Engine: "{{ RDS.DB_ENGINE }}"
        EngineVersion: "{{ RDS.DB_ENGINE_VERSION }}"
        DBInstanceClass: "{{ RDS.FLAVOR }}"
        DBParameterGroupName: "{{ RDS.PARAMETER_GROUP_NAME }}"
        AllocatedStorage: "{{ RDS.DISK }}"
        DBInstanceIdentifier: "{{ RDS.NODE_NAME.DEVELOPMENT }}"
        DBSubnetGroupName: "{{ RDS.SUBNET_GROUP.DEVELOPMENT }}"
        DBSubnet1: "{{ RDS.SUBNET1 }}"
        DBSubnet2: "{{ RDS.SUBNET2 }}"
        VPCSecurityGroups: "{{ RDS.SECURITY_GROUPS }}"
        Route53HostedZoneId: "{{ ROUTE53.QICOO_TOKYO.HOSTED_ZONE_ID }}"
        Route53RDBName: "{{ ROUTE53.QICOO_TOKYO.RDB_NAME.DEVELOPMENT }}"
        Route53HostedZoneName: "{{ ROUTE53.QICOO_TOKYO.HOSTED_ZONE_NAME }}"
     region: "{{ REGION }}"
  tags: "zenbu"
