- name: "Distributed installation on Kubernetes"
    shell: |
       hal config deploy edit --type distributed --account-name aws

- name: "Setup Register S3 Bucket as a halyard Storage"
    shell: |
       hal config storage s3 edit \
           --access-key-id {{ SECRET.AWS.AWS_ACCESS_KEY_ID }} \
           --secret-access-key {{ SECRET.AWS.AWS_SECRET_ACCESS_KEY }} \
           --bucket {{ S3.SPINNAKER.BUCKET }} \
           --region {{ REGION }}

- name: "Setup Register S3 Bucket as a halyard Storage"
    shell: |
       hal config storage edit --type s3

- name: "Setup Slack Extensitons"
    shell: |
       hal config notification slack enable
       hal config notification slack edit \
           --bot-name {{ SLACK.BOT_NAME }} \
           --token {{ SLACK.TOKEN }}

- name: "Create Token File"

- name: "Setup GitHub Extensitons"
    shell: |
       hal config features edit --artifacts true \
       hal config artifact github enable \
       hal config artifact github account add {{ GITHUB.ARTIFACT_ACCOUNT_NAME }} \
           --username {{ GITHUB.ARTIFACT_ACCOUNT_NAME }} \
           --password \
           --token
