- name: "Delete ElastiCache Cluster"
  shell: |
     aws elasticache delete-cache-cluster \
         --cache-cluster-id {{ ELASTIC_CACHE.CLUSTER_NAME }}
  register: result

- debug: var=result.stdout_lines
  when: result | success
  tags:
    - always
