- name: "Delete ElastiCache Cluster"
  cloudformation:
     stack_name: "{{ ELASTIC_CACHE.STACK_NAME }}"
     state: absent
  register: result

- debug: var=result.stdout_lines
  when: result | success
  tags:
    - always
