- name: "Delete ElastiCache Cluster"
  elasticache:
     name: "{{ ELASTIC_CACHE.CLUSTER_NAME }}"
     state: absent
  register: result

- debug: var=result.stdout_lines
  when: result | success
  tags:
    - always
