- name: "Create EKS Cluster"
  shell: |     
     aws rds create-db-instance \ 
        --db-instance-identifier {{ RDS.NODE_NAME }} \
        --db-instance-class {{ RDS.FLAVOR }} \
        --engine MySQL \
        --allocated-storage {{ RDS.DISK }} \
        --master-username {{ RDS.USERNAME }} \
        --master-user-password {{ RDS.PASSWORD }}
  register: result

- debug: var=result.stdout_lines
  when: result | success
  tags:
    - always
