sudo: false
language: bash
addons:
  apt:
    sources:
    - sourceline: 'ppa:duggan/bats'
    packages:
    - bats
    - bc
install: pip install --user ansible
script: bats  ansible-syntax-check.sh 
