sudo: false
language: bash
addons:
  apt:
    sources:
    - sourceline: 'ppa:duggan/bats'
    packages:
    - bats
    - bc
install: 
 - pip install --user ansible
 - ansible-playbook -i localhost, -c local install-git-secrets.yml
script: 
 - bats ansible-syntax-check.sh  
 - git secrets --scan . 
