sudo: false
language: bash
addons:
  apt:
    sources:
    - sourceline: 'ppa:duggan/bats'
    packages:
    - bats
    - bc
install: pip install --user ansible
before_script: touch ~/.vault_password
script: bats ansible-syntax-check.sh 
