language: bash
addons:
  apt:
    sources:
    - sourceline: 'ppa:duggan/bats'
    packages:
    - bats
    - bc
install: 
 - pip install --user ansible
before_script: 
 - echo test > ~/.vault_password
script: 
 - sudo bats travis-check.sh  
