- name: "download"
  become: yes
  #shell: curl {{ AWS_CLI.URL }} -o {{ GET_URL_TEMP_DIRECTORY }}/{{ AWS_CLI.FILE_NAME }}
  get_url: url={{ AWS_CLI.URL }} dest={{ GET_URL_TEMP_DIRECTORY }}

- name: "install"
  become: yes
  shell: python {{ GET_URL_TEMP_DIRECTORY }}/{{ AWS_CLI.FILE_NAME }}

- name: "pip"
  become: yes
  shell: pip install awscli --upgrade --user

- name: "PATH setup"
  become: yes
  shell: echo export PATH=~/.local/bin:$PATH >> ~/.bashrc
