apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: external-dns
  name: external-dns
  namespace: external-dns
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:latest
        args:
        - --source=service
        - --source=ingress
        - --domain-filter=qicoo.tokyo
        - --provider=aws
        - --policy=sync
        - --aws-zone-type=private 
        - --registry=txt
        - --txt-owner-id=my-identifier   
        env:
        - name: AWS_REGION
          value: us-west-2
