- name: Yum Remove OpenJDK 7
  become: yes
  yum:
    name: java-1.7.0-openjdk
    state: absent

- name: Yum install OpenJDK 8
  become: yes
  yum:
    name: java-1.8.0-openjdk
    state: latest

- name: Get Gatling
  get_url: 
    url: https://repo1.maven.org/maven2/io/gatling/highcharts/gatling-charts-highcharts-bundle/3.0.1.1/gatling-charts-highcharts-bundle-3.0.1.1-bundle.zip
    dest: /tmp/gatling-charts-highcharts-bundle-3.0.1.1-bundle.zip
    validate_certs: no
    timeout: 30

- name: Make Gatling Dir
  file:
    dest: ~/gatling
    state: directory
    owner: "{{ GATLING_USER.NAME }}"
    group: "{{ GATLING_USER.GROUP }}"

- name: Unarchive bundle
  unarchive:
    src: /tmp/gatling-charts-highcharts-bundle-3.0.1.1-bundle.zip
    dest: ~/gatling

- name: Copy Scenario Dir
  copy:
    src_dir: /home/qicoo/qicoo-ansible/gatling/files/qicoo
    dest_dir: /home/ec2-user/gatling/gatling-charts-highcharts-bundle-3.0.1.1/user-files/simulations/qicoo


- name: Modify Scenario File Owner
  file:
    path: /home/ec2-user/gatling/gatling-charts-highcharts-bundle-3.0.1.1/user-files/simulations/qicoo
    state: directory
    recurse: yes
    owner: "{{ GATLING_USER.NAME }}"
    group: "{{ GATLING_USER.GROUP }}"
