- name: "Delete Hal Config"
  file:
     path: ~/.hal/config
     state: absent

- name: "Delete Kube Config"
  file:
     path: ~/.kube/config
     state: absent

- name: "Delete EKS Nodes"
  cloudformation:
     stack_name:  {{ EKS.SPINNAKER.EC2_NODEGROUP }} 
     state: "absent"

- name: "Delete Managed Infrastructure"
  cloudformation:
     stack-name: {{ EKS.SPINNAKER.MANAGED_ACOUNT_STACK }}
     state: "absent"

- name: "Delete Managing Infrastructure"
  cloudformation:
    stack-name: {{ EKS.SPINNAKER.MANAGING_ACOUNT_STACK }}
    state: "absent"
