- name: "Create RDS Instance"
  cloudformation:
     stack_name: "{{ ELASTIC_CACHE.STACK_NAME }}"
     template: "{{ ansible_env.PWD }}/files/cloudformaiton-elasticache-withroute53.yaml"
     disable_rollback: true
     template_parameters:
        ClusterName: "{{ ELASTIC_CACHE.CLUSTER_NAME }}"
        Engine: "{{ ELASTIC_CACHE.CACHE_ENGINE }}"
        EngineVersion: "{{ ELASTIC_CACHE.CACHE_ENGINE_VERSION }}"
        NumCacheNodes: "{{ ELASTIC_CACHE.REPLICA_NODES }}"
        CacheNodeType: "{{ ELASTIC_CACHE.CLUSTER_NODE_TYPE }}"
        CacheParameterGroupName: "{{ ELASTIC_CACHE.PARAMETER_GROUP }}"
        CacheSubnetGroupName: "{{ ELASTIC_CACHE.SUBNET_GROUP }}"
        VpcSecurityGroupIds: "{{ ELASTIC_CACHE.SECURITY_GROUP }}"
        Route53HostedZoneId: "{{ ROUTE53. }}"
        Route53ECacheName: "{{ ROUTE53. }}"
        Route53HostedZoneName: "{{ ROUTE53. }}"
  register: result

- debug: var=result.stdout_lines
  when: result | success
  tags:
    - always
