- name: "Create ElastiCache Cluster"
  elasticache:
     name: "{{ ELASTIC_CACHE.CLUSTER_NAME }}"
     state: present
     engine: "{{ ELASTIC_CACHE.CACHE_ENGINE }}"
     cache_engine_version: "{{ ELASTIC_CACHE.CACHE_ENGINE_VERSION }}"
     node_type: "{{ ELASTIC_CACHE.CLUSTER_NODE_TYPE }}"
     num_nodes: "{{ ELASTIC_CACHE.REPLICA_NODES }}"
     region: "{{ REGION }}"
  register: result

- debug: var=result.stdout_lines
  when: result | success
  tags:
    - always
