- name: "Create S3 Bucket"
  shell: |
     aws s3api create-bucket \
         --bucket {{ S3.BUCKET }} \
         --region {{ REGION }}
  register: result

- debug: var=result.stdout_lines
  when: result | success
  tags:
    - always
