- name: "View ec2 instans list"
  shell: |
    aws ec2 describe-instances \
    --query 'Reservations[].Instances[].{PublicIp:PublicIpAddress,PrivateIp:PrivateIpAddress,InstanceId:InstanceId,Name:Tags[?Key==`Name`].Value}'
  register: result

- debug: var=result.stdout_lines
  when: result | success
  tags:
    - always
