- name: "Create EKS Cluster"
  rds:
     command: create
     instance_name: "{{ RDS.NODE_NAME }}"
     db_engine: MySQL
     instance_type: "{{ RDS.FLAVOR }}"
     size: "{{ RDS.DISK }}"
     username: "{{ SECRET.AWS.RDS_MYSQL_USER }}"
     password: "{{ SECRET.AWS.RDS_MYSQL_PASSWORD }}"
     region: "{{ REGION }}"
  register: result

- debug: var=result.stdout_lines
  when: result | success
  tags:
    - always
