- name: "kustomize download"
  become: yes
  get_url: url={{ KUSTOMIZE_CLI.URL }} dest={{ GET_URL_TEMP_DIRECTORY }}

- name: "kustomize chmod"
  become: yes
  file: dest={{ GET_URL_TEMP_DIRECTORY }}/{{ KUSTOMIZE_CLI.FILE_NAME }}_1.0.8_linux_amd64 mode=a+x

- name: "kustomize move"
  become: yse
  shell: mv {{ GET_URL_TEMP_DIRECTORY }}/{{ KUSTOMIZE_CLI.FILE_NAME }}_1.0.8_linux_amd64 /bin/{{ KUSTOMIZE_CLI.FILE_NAME }}
