- name: "Create Ark Backup"
  shell: |
     ark backup create {{ ARK_BACKUP_NAME }} --include-namespaces production,stagement
  register: result

- debug: var=result.stdout_lines
  when: result | success
  tags:
    - always
