- name: "Create Ark Backup"
  shell: |
     ark backup create {{ ARK.BACKUP_NAME }}-{{ lookup('pipe','date +%Y%m%d') }}
  register: result

- debug: var=result.stdout_lines
  when: result | success
  tags:
    - always
