- name: "Create Ark Env"
  shell: |
     kubectl apply -f manifests/main/00-prereqs.yaml

- name: "Create Ark Secret"
  shell: |
     kubectl create secret generic cloud-credentials --namespace heptio-ark --from-file cloud=~/.aws/credentials

- name: "Create Ark Config"
  shell: |
     kubectl apply -f manifests/main/10-ark-config.yaml

- name: "Create Ark Deployment"
  shell: |
     kubectl apply -f manifests/main/20-deployment.yaml
