- name: "Register Last Dir"
  shell: |
    aws s3api list-objects --bucket {{ S3.BACKUP.BUCKET }} | jq -r .Contents[].Key | awk -F '[/]' '{print $1}' | uniq
  register: RESTORE_DIR

- name: "Create Ark Restore"
  shell: |
    ark restore create --from-backup {{ RESTORE_DIR.stdout }} --include-namespaces production,stagement
  register: result

- debug: var=result.stdout_lines
  when: result | success
  tags:
    - always
