- name: "Register Last Dir"
  shell: |
    aws s3api list-objects --bucket {{ S3.BACKUP.BUCKET }} | jq -r .Contents[].Key | grep -v metadata | awk -F '[/]' '{print $2}' | sort -r | head -n1
  register: RESTORE_DIR

- name: "Create Ark Restore"
  shell: |
    ark restore create --include-namespaces {{ ARK.RESTORE_NAMESPACES }} --from-backup {{ RESTORE_DIR.stdout }}
  register: result


- debug: var=result.stdout_lines
  when: result | success
  tags:
    - always
