kind: PersistentVolume
apiVersion: v1
metadata:
  name: ebs-prometheus-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-037d297565d947df9
