AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  AvailabilityZone:
    Type: String
  Size:
    Type: Number
  SnapshotId:
    Type: String
    Default: ""
  VolumeType:
    Type: String
Resources:
  PrometheusDataVolume:
    Type: "AWS::EC2::Volume"
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      Size: !Ref Size
      SnapshotId: !Ref SnapshotId
      VolumeType: !Ref VolumeType
