AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  MasterUsername:
    NoEcho: 'true'
    Type: String
  MasterUserPassword:
    NoEcho: 'true'
    Type: String
  Engine:
    Type: String
  EngineVersion:
    Type: String
  DBInstanceClass:
    Type: String
  DBParameterGroupName:
    Type: String
  AllocatedStorage:
    Type: Number
  DBInstanceIdentifier:
    Type: String
  DBSubnetGroupName:
    Type: String
  DBSubnet1:
    Type: String
  DBSubnet2:
    Type: String
  VPCSecurityGroups:
    Type: String
  Route53HostedZoneId:
    Type: String
  Route53RDBName:
    Type: String
  Route53HostedZoneName:
    Type: String
Resources:
  DatabaseSubnet:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupName : !Ref DBSubnetGroupName
      DBSubnetGroupDescription: !Ref DBSubnetGroupName
      SubnetIds:
        - !Ref DBSubnet1
        - !Ref DBSubnet2
  DatabaseInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      Engine: !Ref Engine
      EngineVersion: !Ref EngineVersion
      DBInstanceClass: !Ref DBInstanceClass
      DBParameterGroupName: !Ref DBParameterGroupName
      AllocatedStorage: !Ref AllocatedStorage
      StorageType: gp2
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      DBSubnetGroupName: !Ref DatabaseSubnet
      PubliclyAccessible: true
      VPCSecurityGroups:
        - !Ref VPCSecurityGroups
      CopyTagsToSnapshot: true
      BackupRetentionPeriod: 7
    DeletionPolicy: Delete
  DatabaseDNSRecord:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneId: !Ref Route53HostedZoneId
      Comment: "CNAME record for the db."
      Name:
        "Fn::Join":
          - ""
          - - !Ref Route53RDBName
            - "."
            - !Ref Route53HostedZoneName
            - "."
      Type: "CNAME"
      TTL: 300
      ResourceRecords:
        - "Fn::GetAtt": ["DatabaseInstance", "Endpoint.Address"]
