AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  MasterUsername:
    NoEcho: 'true'
    Type: String
  MasterUserPassword:
    NoEcho: 'true'
    Type: String
  Engine:
    Type: String
  DBInstanceClass:
    Type: String
  AllocatedStorage:
    Type: Number
  DBInstanceIdentifier:
    Type: String
  DBSubnetGroupName:
    Type: String
  VPCSecurityGroups:
    Type: String
  HostedZoneId:
    Type: String
  Route53RDBName:
    Type: String
  Route53HostedZoneName:
    Type: String
Resources:
  DatabaseInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      Engine: !Ref Engine
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref AllocatedStorage
      StorageType: gp2
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      DBSubnetGroupName: !Ref DBSubnetGroupName
      PubliclyAccessible: true
      VPCSecurityGroups:
        - !Ref VPCSecurityGroups
      CopyTagsToSnapshot: true
      BackupRetentionPeriod: 7
    DeletionPolicy: Snapshot
  DatabaseDNSRecord:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Comment: "CNAME record for the db."
      Name:
        "Fn::Join":
          - ""
          - - !Ref Route53RDBName
            - "."
            - !Ref Route53HostedZoneName
            - "."
      Type: "CNAME"
      TTL: 300
      ResourceRecords:
        - "Fn::GetAtt": ["DatabaseInstance", "Endpoint.Address"]
