apiVersion: ark.heptio.com/v1
kind: Schedule
metadata:
  name: daily
  namespace: heptio-ark
spec:
#  schedule: 4 0 * * *  
  schedule: 5 0 * * *
  template:
    excludedNamespaces: null
    excludedResources: null
    hooks:
      resources: null
    includeClusterResources: null
    includedNamespaces:
    - '*'
    includedResources: null
    labelSelector: null
    snapshotVolumes: true
    ttl: 168h0m0s
